# Site settings for Mohammed Jouhar's Personal Blog
title: "my dataworks – Mohammed Jouhar"
tagline: "Exploring AI, data, and career growth—one post at a time"
email: "dataworks.jouhar@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog sharing practical, easy-to-understand insights in Data Analytics, 
  AI Agents, and career development based on real-world experience. Created to inspire 
  and educate aspiring analysts, data professionals, and curious learners.
baseurl: "/Blog-Post-2025" # the subpath of your site, e.g. /blog
url: "https://dataworksjouhar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: mohammed-jouhar
github_username: 

# Author information
author:
  name: Mohammed Jouhar
  bio: >-
    I’m Mohammed Jouhar. I’ve been working with data for over a decade-across retail, analytics, automation, and AI initiatives. 
    Along the way, I’ve learned that data is more than numbers: it’s about solving problems, telling stories, and helping people make better decisions. 

    This blog is my personal space to share what I’m learning and building-whether it’s SQL, Automation, AI agents, or real project experiences.
    My goal is to keep it simple, practical, and useful for anyone curious about the data world, from beginners to professionals.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  categories:
    output: true
    permalink: /category/:name/

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mohammed Jouhar"
      
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Custom variables
categories:
  - Data Analytics
  - AI Agents & Automation
  - Career Tips
  - Projects & Case Studies
  - Learning Notes
  - Process Automation
  - Data Visualization
  - AI
  - Automation

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
